# DiscordBridge – Beispiel-Settings (bitte in plugins/DiscordBridge/settings.yml anpassen)
discord:
  token: "CHANGE_ME"   # Bot-Token hier eintragen (niemals committen)

channelId: ""
guildId: ""

format:
  minecraftToDiscord: "[%player%] %message%"
  discordToMinecraft: "[Discord] %user%: %message%"

ignoreBots: true
