name: Release

on:
  push:
    tags:
      - "v*.*.*"   # z.B. v1.0.0

permissions:
  contents: write  # nötig, um Release zu erstellen

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Optional: Version aus dem Tag in Gradle reinreichen
      - name: Build shaded jar
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          ./gradlew -Pversion="$TAG" clean shadowJar --stacktrace

      - name: Find artifact
        id: find_jar
        run: |
          FILE=$(ls -1 build/libs/*.jar | head -n1)
          echo "jar=$FILE" >> $GITHUB_OUTPUT
          echo "Chosen JAR: $FILE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.find_jar.outputs.jar }}
